export const TRIVIA_GROUPS = [
    { id: 'english', label: '英文祕密', icon: '🔤', description: '單字、發音與英語文化' },
    { id: 'world', label: '世界探索', icon: '🌍', description: '動物、科學與世界地理' }
];

export const TRIVIA_CATEGORIES = [
    { id: 'word_origins', group: 'english', label: '單字由來', icon: '📜', color: 'text-yellow-300' },
    { id: 'spelling_sounds', group: 'english', label: '拼字與發音', icon: '🎧', color: 'text-cyan-300' },
    { id: 'english_culture', group: 'english', label: '英語文化', icon: '🗣️', color: 'text-purple-300' },
    { id: 'nature_animals', group: 'world', label: '動物與自然', icon: '🦋', color: 'text-green-300' },
    { id: 'science_space', group: 'world', label: '科學與太空', icon: '🚀', color: 'text-blue-300' },
    { id: 'world_places', group: 'world', label: '世界與地理', icon: '🗺️', color: 'text-orange-300' }
];

export const TRIVIA_SOURCES = {
    word_origins: { label: 'Merriam-Webster 與 Online Etymology Dictionary', url: 'https://www.merriam-webster.com/words-at-play' },
    spelling_sounds: { label: 'Cambridge Dictionary Pronunciation', url: 'https://dictionary.cambridge.org/grammar/british-grammar/pronunciation' },
    english_culture: { label: 'Cambridge Grammar：英式與美式英文', url: 'https://dictionary.cambridge.org/grammar/british-grammar/british-and-american-english' },
    nature_animals: { label: 'Smithsonian 與 NOAA 動物／海洋資料', url: 'https://oceanservice.noaa.gov/facts/' },
    science_space: { label: 'NASA Solar System Facts', url: 'https://science.nasa.gov/solar-system/solar-system-facts/' },
    world_places: { label: 'USGS 與 Encyclopaedia Britannica 地理資料', url: 'https://www.usgs.gov/science/science-explorer' }
};

export const TRIVIA_CARDS = [
    // 英文祕密：單字由來（20）
    { id: 'english-origin-01', group: 'english', category: 'word_origins', title: 'alphabet 的開頭', text: 'alphabet 這個字來自希臘字母表前兩個字母 alpha 和 beta。' },
    { id: 'english-origin-02', group: 'english', category: 'word_origins', title: 'emoji 不是 emotion', text: 'emoji 來自日文「繪」和「文字」，只是剛好看起來很像英文 emotion。' },
    { id: 'english-origin-03', group: 'english', category: 'word_origins', title: 'robot 原本是苦工', text: 'robot 來自捷克語 robota，帶有被迫勞動或苦工的意思。' },
    { id: 'english-origin-04', group: 'english', category: 'word_origins', title: 'quarantine 的 40', text: 'quarantine 和義大利語「四十天」有關，早期船隻會被隔離一段時間以防疾病傳播。' },
    { id: 'english-origin-05', group: 'english', category: 'word_origins', title: 'breakfast 在打破什麼？', text: 'breakfast 就是 break 加 fast，意思是結束一整夜沒有進食的狀態。' },
    { id: 'english-origin-06', group: 'english', category: 'word_origins', title: 'goodbye 的祝福', text: 'goodbye 是 God be with ye 逐漸縮短、變化而來的告別語。' },
    { id: 'english-origin-07', group: 'english', category: 'word_origins', title: 'sandwich 是人名', text: 'sandwich 以英國的 Sandwich 伯爵命名，後來成為夾餡麵包的名稱。' },
    { id: 'english-origin-08', group: 'english', category: 'word_origins', title: 'window 是風之眼', text: 'window 的早期字源和古北歐語的「風之眼」有關，形容牆上讓風與光進入的開口。' },
    { id: 'english-origin-09', group: 'english', category: 'word_origins', title: 'clue 原本是一團線', text: 'clue 以前也寫作 clew，原意是一團線；故事裡的線能帶人走出迷宮，後來變成「線索」。' },
    { id: 'english-origin-10', group: 'english', category: 'word_origins', title: 'muscle 像小老鼠', text: 'muscle 來自拉丁語「小老鼠」，古人覺得肌肉在皮膚下移動的樣子像老鼠。' },
    { id: 'english-origin-11', group: 'english', category: 'word_origins', title: 'companion 一起吃麵包', text: 'companion 的字源包含「一起」和「麵包」，原本指一起分享食物的人。' },
    { id: 'english-origin-12', group: 'english', category: 'word_origins', title: 'candidate 穿白衣', text: 'candidate 和拉丁語的「潔白」有關，古羅馬的候選人會穿著特別處理過的白袍。' },
    { id: 'english-origin-13', group: 'english', category: 'word_origins', title: 'disaster 是壞星象', text: 'disaster 的字源可拆成「不好的」和「星星」，反映古人把災禍和星象聯繫在一起。' },
    { id: 'english-origin-14', group: 'english', category: 'word_origins', title: '& 也有名字', text: '& 叫做 ampersand，它的形狀是拉丁文 et（and）長期連寫形成的。' },
    { id: 'english-origin-15', group: 'english', category: 'word_origins', title: '大小寫來自盒子', text: 'uppercase 和 lowercase 來自早期印刷工坊：大寫鉛字放在上層盒子，小寫放在下層盒子。' },
    { id: 'english-origin-16', group: 'english', category: 'word_origins', title: '先有水果才有顏色', text: '英文 orange 先是水果名稱，後來才成為橘色的顏色名稱。' },
    { id: 'english-origin-17', group: 'english', category: 'word_origins', title: '三組連續雙字母', text: 'bookkeeper 有 oo、kk、ee 三組連續的雙字母，是很少見的拼字。' },
    { id: 'english-origin-18', group: 'english', category: 'word_origins', title: '15 個字母不重複', text: 'uncopyrightable 有 15 個字母，而且沒有任何字母重複。' },
    { id: 'english-origin-19', group: 'english', category: 'word_origins', title: 'queue 只聽見一個字母', text: 'queue 的發音和字母 Q 相同，後面的 ueue 在現代英語發音中都沒有各自發聲。' },
    { id: 'english-origin-20', group: 'english', category: 'word_origins', title: '矛盾修辭本身也矛盾', text: 'oxymoron 指把看似矛盾的詞放在一起；它的希臘字源本身就有「敏銳」與「愚鈍」的組合。' },

    // 英文祕密：拼字與發音（15）
    { id: 'english-sound-01', group: 'english', category: 'spelling_sounds', title: '最常出現的弱母音', text: 'schwa 寫作 /ə/，常出現在沒有重音的音節，例如 about 的第一個音。' },
    { id: 'english-sound-02', group: 'english', category: 'spelling_sounds', title: '重音不只是大聲', text: '英文重音通常同時包含較清楚的母音、較長的時間和音高變化，不只是把聲音放大。' },
    { id: 'english-sound-03', group: 'english', category: 'spelling_sounds', title: 'REcord 與 reCORD', text: 'record 當名詞時常把重音放前面，當動詞時常放後面；重音可能幫助分辨詞性。' },
    { id: 'english-sound-04', group: 'english', category: 'spelling_sounds', title: '複數 s 有三種聲音', text: '英文複數字尾常讀成 /s/、/z/ 或 /ɪz/，要看前一個聲音，而不是只看字母。' },
    { id: 'english-sound-05', group: 'english', category: 'spelling_sounds', title: '過去式 ed 也有三種', text: '規則動詞的 -ed 常讀成 /t/、/d/ 或 /ɪd/，例如 worked、played、wanted。' },
    { id: 'english-sound-06', group: 'english', category: 'spelling_sounds', title: 'th 有兩種聲帶狀態', text: 'think 的 th 不振動聲帶，this 的 th 會振動；兩者的舌頭位置很接近。' },
    { id: 'english-sound-07', group: 'english', category: 'spelling_sounds', title: 'kn 的 k 通常沉默', text: 'know、knee、knife 開頭的 k 在現代英語通常不發音。' },
    { id: 'english-sound-08', group: 'english', category: 'spelling_sounds', title: 'mb 結尾的 b', text: 'lamb、climb、thumb 結尾的 b 通常不發音，但字母仍保留在拼字中。' },
    { id: 'english-sound-09', group: 'english', category: 'spelling_sounds', title: 'gh 最會變化', text: 'gh 在 night 中不發音，在 laugh 中可讀 /f/，在 ghost 中則是 /g/ 的一部分。' },
    { id: 'english-sound-10', group: 'english', category: 'spelling_sounds', title: 'c 的常見規律', text: 'c 在 e、i、y 前常讀 /s/，其他位置常讀 /k/，例如 city 和 cat。' },
    { id: 'english-sound-11', group: 'english', category: 'spelling_sounds', title: 'g 有規律也有例外', text: 'g 在 e、i、y 前常讀 /dʒ/，但 get、give 等常用字是明顯例外。' },
    { id: 'english-sound-12', group: 'english', category: 'spelling_sounds', title: 'ch 不只一種讀法', text: 'ch 在 chair 常讀 /tʃ/，在 chemistry 常讀 /k/，在 machine 常讀 /ʃ/。' },
    { id: 'english-sound-13', group: 'english', category: 'spelling_sounds', title: 'x 也能變聲', text: 'x 在 box 常讀 /ks/，在 exam 常讀 /gz/，在 xylophone 開頭常讀 /z/。' },
    { id: 'english-sound-14', group: 'english', category: 'spelling_sounds', title: 'oo 不保證同音', text: 'food 和 foot 都有 oo，但母音不同；英文拼字不能永遠直接預測發音。' },
    { id: 'english-sound-15', group: 'english', category: 'spelling_sounds', title: '同拼字也可能不同音', text: 'lead 可以是「帶領」/liːd/，也可以是金屬「鉛」/led/，要靠句子判斷。' },

    // 英文祕密：英語文化（15）
    { id: 'english-culture-01', group: 'english', category: 'english_culture', title: 'flat 與 apartment', text: '英式英文常說 flat，美式英文常說 apartment，兩者都可以表示公寓住宅。' },
    { id: 'english-culture-02', group: 'english', category: 'english_culture', title: 'lift 與 elevator', text: '英式英文常說 lift，美式英文常說 elevator。' },
    { id: 'english-culture-03', group: 'english', category: 'english_culture', title: 'chips 到底是哪一種？', text: '英國的 chips 通常是炸薯條；美國的 chips 通常是薄脆薯片。' },
    { id: 'english-culture-04', group: 'english', category: 'english_culture', title: '英國的 crisps', text: '英國人常用 crisps 指袋裝薄薯片，美國人通常稱它們 potato chips。' },
    { id: 'english-culture-05', group: 'english', category: 'english_culture', title: 'football 與 soccer', text: '世界許多地方的 football 指足球；在美國，football 通常指美式足球，足球常叫 soccer。' },
    { id: 'english-culture-06', group: 'english', category: 'english_culture', title: 'colour 和 color 都對', text: 'colour 常見於英式拼字，color 常見於美式拼字；差異不代表其中一個必然錯誤。' },
    { id: 'english-culture-07', group: 'english', category: 'english_culture', title: 'centre 和 center', text: 'centre 是常見英式拼字，center 是常見美式拼字。' },
    { id: 'english-culture-08', group: 'english', category: 'english_culture', title: 'travelled 和 traveled', text: '英式英文常寫 travelled，美式英文通常寫 traveled；兩邊的雙寫規則略有差異。' },
    { id: 'english-culture-09', group: 'english', category: 'english_culture', title: 'autumn 和 fall 都很老', text: 'autumn 和 fall 都能表示秋天；fall 並不是現代美國才新造出的詞。' },
    { id: 'english-culture-10', group: 'english', category: 'english_culture', title: 'pants 的英美差異', text: '美式英文的 pants 通常是長褲；英式英文的 pants 常指內褲，長褲常叫 trousers。' },
    { id: 'english-culture-11', group: 'english', category: 'english_culture', title: 'first floor 不一定同一層', text: '美國的 first floor 通常是地面層；英國常把地面層叫 ground floor，上一層才是 first floor。' },
    { id: 'english-culture-12', group: 'english', category: 'english_culture', title: 'biscuit 和 cookie', text: '英國的 biscuit 範圍包含許多甜脆點心；美國的 biscuit 也可能指一種鬆軟鹹麵包。' },
    { id: 'english-culture-13', group: 'english', category: 'english_culture', title: 'holiday 和 vacation', text: '英式英文常用 holiday 表示休假旅行；美式英文更常用 vacation。' },
    { id: 'english-culture-14', group: 'english', category: 'english_culture', title: 'queue 和 line', text: '排隊在英式英文常說 queue，在美式英文常說 stand in line 或 wait in line。' },
    { id: 'english-culture-15', group: 'english', category: 'english_culture', title: 'postcode 和 ZIP code', text: '英國地址使用 postcode；美國使用 ZIP code。' },

    // 世界探索：動物與自然（20）
    { id: 'world-nature-01', group: 'world', category: 'nature_animals', title: '章魚有三顆心臟', text: '章魚有三顆心臟，血液中的含銅蛋白讓牠們的血呈現藍色。' },
    { id: 'world-nature-02', group: 'world', category: 'nature_animals', title: '蜂鳥能向後飛', text: '蜂鳥特殊的翅膀轉動方式，讓牠們能懸停，也能真正向後飛行。' },
    { id: 'world-nature-03', group: 'world', category: 'nature_animals', title: '蝴蝶用腳品嚐', text: '蝴蝶腳部帶有味覺感受器，停在植物上時就能判斷是否適合產卵或進食。' },
    { id: 'world-nature-04', group: 'world', category: 'nature_animals', title: '海馬爸爸負責懷孕', text: '雌海馬把卵放入雄海馬的育兒袋，胚胎會在雄海馬體內發育後出生。' },
    { id: 'world-nature-05', group: 'world', category: 'nature_animals', title: '紅鶴的粉紅來自食物', text: '紅鶴吃下藻類與小型甲殼類中的色素，羽毛才會逐漸呈現粉紅或橘紅色。' },
    { id: 'world-nature-06', group: 'world', category: 'nature_animals', title: '北極熊其實是黑皮膚', text: '北極熊的皮膚是黑色，毛則大致透明；光線散射讓整身毛看起來像白色。' },
    { id: 'world-nature-07', group: 'world', category: 'nature_animals', title: '長頸鹿也只有七節頸椎', text: '長頸鹿和人類一樣通常有七節頸椎，只是每一節都拉得非常長。' },
    { id: 'world-nature-08', group: 'world', category: 'nature_animals', title: '海豚可以半腦睡覺', text: '海豚睡眠時能讓一側大腦休息、另一側保持警覺，以便呼吸與注意周遭。' },
    { id: 'world-nature-09', group: 'world', category: 'nature_animals', title: '烏鴉記得人臉', text: '研究發現烏鴉能長期辨認曾帶來威脅的人臉，也可能把警戒訊息傳給同伴。' },
    { id: 'world-nature-10', group: 'world', category: 'nature_animals', title: '六角恐龍很會再生', text: '六角恐龍（墨西哥鈍口螈）能再生四肢，也能修復部分脊髓、心臟等組織。' },
    { id: 'world-nature-11', group: 'world', category: 'nature_animals', title: '木蛙可以結冰後甦醒', text: '木蛙冬眠時身體的一部分能結冰，體內糖分會協助保護細胞，回暖後再恢復活動。' },
    { id: 'world-nature-12', group: 'world', category: 'nature_animals', title: '袋熊便便是方塊形', text: '袋熊的腸道會用不同速度與壓力塑形，使排出的糞便帶有近似方塊的形狀。' },
    { id: 'world-nature-13', group: 'world', category: 'nature_animals', title: '無尾熊也有指紋', text: '無尾熊指尖有細密紋路，外觀看起來和人類指紋非常相似。' },
    { id: 'world-nature-14', group: 'world', category: 'nature_animals', title: '鯊魚家族比樹木更早', text: '鯊魚祖先在約四億年前已經出現，比最早形成森林的大型樹木還早。' },
    { id: 'world-nature-15', group: 'world', category: 'nature_animals', title: '藍鯨是已知最大動物', text: '藍鯨是目前已知曾存在過體型最大的動物，體長可以超過 25 公尺。' },
    { id: 'world-nature-16', group: 'world', category: 'nature_animals', title: '企鵝爸爸站著孵蛋', text: '雄性皇帝企鵝會把蛋放在腳上，用腹部皮膚覆蓋，在寒冬中負責孵化。' },
    { id: 'world-nature-17', group: 'world', category: 'nature_animals', title: '海星沒有中央大腦', text: '海星沒有像人類一樣的中央大腦，而是利用環繞身體的神經網控制活動。' },
    { id: 'world-nature-18', group: 'world', category: 'nature_animals', title: '蜜蜂用舞蹈報路', text: '蜜蜂的搖擺舞能向同伴傳達食物大致方向與距離。' },
    { id: 'world-nature-19', group: 'world', category: 'nature_animals', title: '鴨嘴獸能感應電場', text: '鴨嘴獸閉上眼睛和耳朵潛水時，能用嘴部感受獵物肌肉產生的微弱電訊號。' },
    { id: 'world-nature-20', group: 'world', category: 'nature_animals', title: '獵豹不會像獅子大吼', text: '獵豹的喉部構造不同於獅子和老虎，牠們會發出呼嚕、啁啾等聲音，但不會真正咆哮。' },

    // 世界探索：科學與太空（15）
    { id: 'world-space-01', group: 'world', category: 'science_space', title: '金星才是最熱行星', text: '雖然水星離太陽最近，金星濃厚大氣造成的溫室效應讓它成為太陽系最熱的行星。' },
    { id: 'world-space-02', group: 'world', category: 'science_space', title: '金星的一天比一年久', text: '金星自轉非常慢，轉一圈所需時間比它繞太陽公轉一圈還長。' },
    { id: 'world-space-03', group: 'world', category: 'science_space', title: '水星一年只有 88 天', text: '水星只需要大約 88 個地球日，就能繞太陽完成一圈。' },
    { id: 'world-space-04', group: 'world', category: 'science_space', title: '天王星像躺著轉', text: '天王星的自轉軸傾斜接近 90 度，看起來就像側躺著繞太陽運行。' },
    { id: 'world-space-05', group: 'world', category: 'science_space', title: '太陽包辦幾乎全部質量', text: '太陽約占整個太陽系總質量的 99.8%，它的重力維繫著行星與小天體的軌道。' },
    { id: 'world-space-06', group: 'world', category: 'science_space', title: '陽光要旅行八分鐘', text: '太陽光抵達地球大約需要 8 分 20 秒，所以我們看到的是幾分鐘前的太陽。' },
    { id: 'world-space-07', group: 'world', category: 'science_space', title: '太陽系也在繞圈', text: '太陽系繞銀河系中心一圈約需 2.3 億年，這段時間也稱為一個銀河年。' },
    { id: 'world-space-08', group: 'world', category: 'science_space', title: '木星能裝進上千個地球', text: '如果把木星想成空心球體，內部空間大約能容納一千個地球。' },
    { id: 'world-space-09', group: 'world', category: 'science_space', title: '土星平均密度比水低', text: '土星整體平均密度低於液態水；但現實中沒有大到能讓土星漂浮的水池。' },
    { id: 'world-space-10', group: 'world', category: 'science_space', title: '火星有巨型火山', text: '火星的奧林帕斯山是太陽系已知最大的火山之一，高度約為聖母峰的兩倍多。' },
    { id: 'world-space-11', group: 'world', category: 'science_space', title: '真空中聽不到聲音', text: '聲音需要物質振動來傳播，太空近乎真空，因此不能像在空氣中一樣傳送聲音。' },
    { id: 'world-space-12', group: 'world', category: 'science_space', title: '月球每年離遠一點', text: '雷射測距顯示，月球平均每年離地球遠約 3.8 公分。' },
    { id: 'world-space-13', group: 'world', category: 'science_space', title: '太空站一天看很多次日出', text: '國際太空站大約 90 分鐘繞地球一圈，太空人一天能看到約 16 次日出與日落。' },
    { id: 'world-space-14', group: 'world', category: 'science_space', title: '月球腳印能留很久', text: '月球幾乎沒有會吹散痕跡的風雨，因此太空人的腳印可能保存非常久。' },
    { id: 'world-space-15', group: 'world', category: 'science_space', title: '兩顆行星沒有月亮', text: '太陽系八大行星中，只有水星和金星沒有天然衛星。' },

    // 世界探索：世界與地理（15）
    { id: 'world-place-01', group: 'world', category: 'world_places', title: '南極洲是最大沙漠', text: '沙漠是以降水稀少判斷，不是以溫度判斷；寒冷乾燥的南極洲因此是世界最大沙漠。' },
    { id: 'world-place-02', group: 'world', category: 'world_places', title: '非洲跨越四個半球', text: '赤道與本初子午線都穿過非洲，因此非洲同時位於東、西、南、北四個半球。' },
    { id: 'world-place-03', group: 'world', category: 'world_places', title: '太平洋最大也最深', text: '太平洋是地球面積最大的海洋，也包含已知最深的馬里亞納海溝。' },
    { id: 'world-place-04', group: 'world', category: 'world_places', title: '貝加爾湖深超過一公里', text: '俄羅斯的貝加爾湖是世界最深的湖泊，最深處超過 1,600 公尺。' },
    { id: 'world-place-05', group: 'world', category: 'world_places', title: '死海岸邊低於海平面', text: '死海沿岸是地球陸地表面最低的地區之一，位置低於平均海平面四百多公尺。' },
    { id: 'world-place-06', group: 'world', category: 'world_places', title: '聖母峰是海拔最高峰', text: '以平均海平面為基準，聖母峰是地球上海拔最高的山峰。' },
    { id: 'world-place-07', group: 'world', category: 'world_places', title: '從山腳量，冒納凱亞更高', text: '夏威夷冒納凱亞火山大部分藏在海面下；從海底山腳量到山頂，總高度超過聖母峰。' },
    { id: 'world-place-08', group: 'world', category: 'world_places', title: '賴索托被一國包圍', text: '賴索托整個國土都被南非包圍，是世界少數完全位於另一個國家內的主權國家。' },
    { id: 'world-place-09', group: 'world', category: 'world_places', title: '伊斯坦堡橫跨兩洲', text: '土耳其的伊斯坦堡分布在博斯普魯斯海峽兩岸，一側在歐洲、另一側在亞洲。' },
    { id: 'world-place-10', group: 'world', category: 'world_places', title: '巴拿馬運河連接兩大洋', text: '巴拿馬運河讓船隻能在大西洋與太平洋之間穿越，不必繞過南美洲南端。' },
    { id: 'world-place-11', group: 'world', category: 'world_places', title: '尼泊爾國旗不是四邊形', text: '尼泊爾是目前唯一使用非四邊形國旗的國家，旗面由兩個相疊的三角形組成。' },
    { id: 'world-place-12', group: 'world', category: 'world_places', title: '俄羅斯跨越 11 個時區', text: '俄羅斯國土橫跨歐亞大陸，官方時間劃分涵蓋 11 個時區。' },
    { id: 'world-place-13', group: 'world', category: 'world_places', title: '梵蒂岡是最小國家', text: '梵蒂岡城國位於羅馬市內，是世界上面積最小的獨立主權國家。' },
    { id: 'world-place-14', group: 'world', category: 'world_places', title: '換日線不是直線', text: '國際換日線大致沿著 180 度經線，但會彎曲繞過國家與島群，避免同一國出現兩個日期。' },
    { id: 'world-place-15', group: 'world', category: 'world_places', title: '赤道附近晝夜很平均', text: '靠近赤道的地區全年白天與黑夜長度變化較小，通常都接近 12 小時。' },

    // 英文祕密加碼：單字由來（21－40）
    { id: 'english-origin-21', group: 'english', category: 'word_origins', title: 'avocado 來自納瓦特爾語', text: 'avocado 經由西班牙語進入英文，更早可追溯到中美洲的納瓦特爾語。' },
    { id: 'english-origin-22', group: 'english', category: 'word_origins', title: 'dollar 來自山谷銀幣', text: 'dollar 和德語 thaler 有關，原本是以波希米亞一處山谷命名的銀幣。' },
    { id: 'english-origin-23', group: 'english', category: 'word_origins', title: 'denim 藏著法國城市', text: 'denim 來自法文 de Nîmes，意思是「來自尼姆」，指和這座城市有關的布料。' },
    { id: 'english-origin-24', group: 'english', category: 'word_origins', title: 'jeans 藏著義大利城市', text: 'jeans 的名稱和義大利港口城市 Genoa（熱那亞）有關，當地曾以耐用布料聞名。' },
    { id: 'english-origin-25', group: 'english', category: 'word_origins', title: 'piano 原本更長', text: 'piano 是 pianoforte 的簡稱，名稱指出這種樂器能彈出柔和與響亮的聲音。' },
    { id: 'english-origin-26', group: 'english', category: 'word_origins', title: 'nickname 多出了一個 n', text: 'nickname 早期來自 an eke-name，連讀久了，前面的 n 被重新分到後面的單字。' },
    { id: 'english-origin-27', group: 'english', category: 'word_origins', title: 'helicopter 不是 heli 加 copter', text: 'helicopter 由希臘語中表示螺旋與翅膀的部分組成，正確字源切法不是 heli 和 copter。' },
    { id: 'english-origin-28', group: 'english', category: 'word_origins', title: 'telephone 是遠方的聲音', text: 'telephone 的希臘字根 tele 表示遠方，phone 表示聲音。' },
    { id: 'english-origin-29', group: 'english', category: 'word_origins', title: 'microscope 看見微小事物', text: 'microscope 的字根分別帶有「微小」和「觀看」的意思。' },
    { id: 'english-origin-30', group: 'english', category: 'word_origins', title: 'photograph 是用光畫畫', text: 'photograph 的希臘字根帶有「光」與「書寫、描畫」的意思。' },
    { id: 'english-origin-31', group: 'english', category: 'word_origins', title: 'dinosaur 是可怕的蜥蜴', text: 'dinosaur 由希臘字根組成，原意大致是「可怕的蜥蜴」。' },
    { id: 'english-origin-32', group: 'english', category: 'word_origins', title: 'galaxy 和牛奶有關', text: 'galaxy 來自希臘語的「牛奶」，也呼應英文把銀河稱為 Milky Way。' },
    { id: 'english-origin-33', group: 'english', category: 'word_origins', title: 'cereal 來自女神名字', text: 'cereal 以羅馬農業女神 Ceres 命名，後來用來稱呼穀類食物。' },
    { id: 'english-origin-34', group: 'english', category: 'word_origins', title: 'volcano 來自火神', text: 'volcano 的名稱和羅馬神話中的火神 Vulcan 有關。' },
    { id: 'english-origin-35', group: 'english', category: 'word_origins', title: 'mentor 原本是角色名字', text: 'mentor 來自古希臘史詩中的人物 Mentor，後來成為可信賴指導者的通稱。' },
    { id: 'english-origin-36', group: 'english', category: 'word_origins', title: 'panic 和牧神 Pan 有關', text: 'panic 的字源和希臘神話中的 Pan 有關，傳說他突如其來的聲音會引起恐慌。' },
    { id: 'english-origin-37', group: 'english', category: 'word_origins', title: 'atlas 原本扛著天空', text: 'atlas 來自希臘神話的 Atlas；地圖集借用了他支撐天空與世界的形象。' },
    { id: 'english-origin-38', group: 'english', category: 'word_origins', title: 'marathon 是地名', text: 'marathon 來自希臘的馬拉松地區，現代長跑名稱和古代戰役傳說相連。' },
    { id: 'english-origin-39', group: 'english', category: 'word_origins', title: 'boycott 是人的姓氏', text: 'boycott 來自 Charles Boycott 的姓氏，後來變成聯合拒絕往來的動詞與名詞。' },
    { id: 'english-origin-40', group: 'english', category: 'word_origins', title: 'telescope 望向遠方', text: 'telescope 的希臘字根帶有「遠方」與「觀看」的意思。' },

    // 英文祕密加碼：拼字與發音（16－30）
    { id: 'english-sound-16', group: 'english', category: 'spelling_sounds', title: 'wr 開頭的 w 不發音', text: 'write、wrong、wrist 開頭的 w 在現代英語通常不發音。' },
    { id: 'english-sound-17', group: 'english', category: 'spelling_sounds', title: '有些 h 會安靜', text: 'hour、honest、heir 開頭的 h 通常不發音，所以前面會使用 an。' },
    { id: 'english-sound-18', group: 'english', category: 'spelling_sounds', title: 'island 的 s 不發音', text: 'island 中的 s 不發音；這個字的拼字曾受其他相似字影響而加入 s。' },
    { id: 'english-sound-19', group: 'english', category: 'spelling_sounds', title: 'rhythm 沒有傳統母音字母', text: 'rhythm 沒有 a、e、i、o、u，但 y 在其中負責表示母音。' },
    { id: 'english-sound-20', group: 'english', category: 'spelling_sounds', title: 'a 或 an 要聽聲音', text: 'a 和 an 取決於下一個字的開頭聲音，所以是 an hour，卻是 a university。' },
    { id: 'english-sound-21', group: 'english', category: 'spelling_sounds', title: 'photograph 會移動重音', text: 'photograph、photography、photographic 的重音位置不同，字形相近也不保證重音相同。' },
    { id: 'english-sound-22', group: 'english', category: 'spelling_sounds', title: 'ough 有很多聲音', text: 'though、through、rough、thought 都有 ough，發音卻不相同。' },
    { id: 'english-sound-23', group: 'english', category: 'spelling_sounds', title: 'tear 可以同字不同音', text: 'tear 表示眼淚與撕裂時的拼字相同，但發音與意思不同。' },
    { id: 'english-sound-24', group: 'english', category: 'spelling_sounds', title: 'wind 也有兩種念法', text: 'wind 表示風與纏繞時，拼字相同但母音不同，要從句子判斷。' },
    { id: 'english-sound-25', group: 'english', category: 'spelling_sounds', title: '美式 t 有時像快速的 d', text: '許多美式口音中，water 或 better 中間的 t 會變成很短的閃音，聽起來接近快速的 d。' },
    { id: 'english-sound-26', group: 'english', category: 'spelling_sounds', title: '句子不是每個字都一樣重', text: '英文句子通常把名詞、主要動詞等資訊字說得較重，文法功能字常會弱化。' },
    { id: 'english-sound-27', group: 'english', category: 'spelling_sounds', title: '語調也會改變訊息', text: '相同句子使用上升或下降語調，可能表達疑問、確認、驚訝或完成感。' },
    { id: 'english-sound-28', group: 'english', category: 'spelling_sounds', title: 'ship 和 sheep 不只差長短', text: 'ship 與 sheep 的母音除了長度不同，舌頭位置與音質也不同。' },
    { id: 'english-sound-29', group: 'english', category: 'spelling_sounds', title: 'can 在句中常變弱', text: 'can 沒有被強調時，母音常弱化；否定的 can’t 通常比較容易被聽見。' },
    { id: 'english-sound-30', group: 'english', category: 'spelling_sounds', title: '英語有很多不同口音', text: '英語沒有唯一的自然口音；不同地區的母語者會使用不同的節奏、母音與語調。' },

    // 英文祕密加碼：英語文化（16－30）
    { id: 'english-culture-16', group: 'english', category: 'english_culture', title: 'pavement 和 sidewalk', text: '英國常用 pavement 表示人行道，美國更常用 sidewalk。' },
    { id: 'english-culture-17', group: 'english', category: 'english_culture', title: 'lorry 和 truck', text: '英國常把大型貨車叫 lorry，美國通常叫 truck。' },
    { id: 'english-culture-18', group: 'english', category: 'english_culture', title: '汽車 boot 不是靴子', text: '英式英文的 car boot 是汽車行李箱，美式英文通常說 trunk。' },
    { id: 'english-culture-19', group: 'english', category: 'english_culture', title: 'petrol 和 gasoline', text: '英國加油常說 petrol，美國通常說 gasoline 或 gas。' },
    { id: 'english-culture-20', group: 'english', category: 'english_culture', title: 'underground 和 subway', text: '英國城市軌道常稱 underground 或 tube，美國更常使用 subway。' },
    { id: 'english-culture-21', group: 'english', category: 'english_culture', title: 'mobile phone 和 cell phone', text: '英國常說 mobile phone，美國常說 cell phone。' },
    { id: 'english-culture-22', group: 'english', category: 'english_culture', title: 'rubbish 和 garbage', text: '英國常用 rubbish 表示垃圾，美國常用 garbage 或 trash。' },
    { id: 'english-culture-23', group: 'english', category: 'english_culture', title: 'torch 也可能是手電筒', text: '英式英文的 torch 常指手電筒，美式英文通常說 flashlight。' },
    { id: 'english-culture-24', group: 'english', category: 'english_culture', title: 'timetable 和 schedule', text: '英國談課表或時刻表常說 timetable，美國更常用 schedule。' },
    { id: 'english-culture-25', group: 'english', category: 'english_culture', title: 'maths 和 math', text: '英式英文常把 mathematics 簡稱 maths，美式英文通常簡稱 math。' },
    { id: 'english-culture-26', group: 'english', category: 'english_culture', title: 'shop 和 store', text: '兩者都能表示商店，但日常美式英文通常更常說 store。' },
    { id: 'english-culture-27', group: 'english', category: 'english_culture', title: 'trainers 和 sneakers', text: '英國常把運動鞋叫 trainers，美國常說 sneakers。' },
    { id: 'english-culture-28', group: 'english', category: 'english_culture', title: 'jumper 和 sweater', text: '英式英文的 jumper 常指套頭毛衣，美式英文通常說 sweater。' },
    { id: 'english-culture-29', group: 'english', category: 'english_culture', title: '日期順序可能不同', text: '英國常寫日、月、年；美國常寫月、日、年，因此純數字日期容易造成誤會。' },
    { id: 'english-culture-30', group: 'english', category: 'english_culture', title: 'team 可以搭配不同動詞', text: '英式英文較常把 team 等集合名詞視為複數，美式英文通常較常視為單數。' },

    // 世界探索加碼：動物與自然（21－40）
    { id: 'world-nature-21', group: 'world', category: 'nature_animals', title: '貓頭鷹眼睛像管子', text: '貓頭鷹的眼睛呈管狀、無法像人眼大幅轉動，因此牠們會轉頭改變視線。' },
    { id: 'world-nature-22', group: 'world', category: 'nature_animals', title: '青蛙用皮膚吸水', text: '許多青蛙不靠嘴巴喝水，而是透過腹部與腿部附近的皮膚吸收水分。' },
    { id: 'world-nature-23', group: 'world', category: 'nature_animals', title: '蝙蝠是真正飛行的哺乳類', text: '蝙蝠是唯一能持續主動飛行的哺乳類；飛鼠只是利用皮膜滑翔。' },
    { id: 'world-nature-24', group: 'world', category: 'nature_animals', title: '鯨鯊是最大的魚', text: '鯨鯊雖然名字有鯨，實際上是鯊魚，也是目前體型最大的魚類。' },
    { id: 'world-nature-25', group: 'world', category: 'nature_animals', title: '樹懶毛上能長藻類', text: '樹懶行動緩慢，粗糙毛髮能形成適合藻類生長的微小環境。' },
    { id: 'world-nature-26', group: 'world', category: 'nature_animals', title: '山羊瞳孔像橫線', text: '山羊的瞳孔接近水平長方形，能提供寬廣視野，幫助注意四周威脅。' },
    { id: 'world-nature-27', group: 'world', category: 'nature_animals', title: '貓不太能嚐到甜味', text: '家貓缺少正常運作的甜味受器之一，因此不像人類一樣感受到典型甜味。' },
    { id: 'world-nature-28', group: 'world', category: 'nature_animals', title: '蛇用舌頭收集氣味', text: '蛇伸出分叉舌頭收集空氣與地面的化學粒子，再送到口腔中的感覺器官分析。' },
    { id: 'world-nature-29', group: 'world', category: 'nature_animals', title: '駱駝有三層眼瞼', text: '駱駝有多層眼瞼與長睫毛，能在風沙環境中保護眼睛。' },
    { id: 'world-nature-30', group: 'world', category: 'nature_animals', title: '海獺會使用石頭', text: '海獺會把石頭當工具，敲開貝類等有硬殼的食物。' },
    { id: 'world-nature-31', group: 'world', category: 'nature_animals', title: '大象不會四腳同時離地跳躍', text: '大象的體型與腿部構造適合穩定承重，不會像許多動物一樣四腳同時離地跳躍。' },
    { id: 'world-nature-32', group: 'world', category: 'nature_animals', title: '螞蟻沒有肺', text: '螞蟻透過身體側邊的小孔與氣管系統交換氣體，不使用像人類一樣的肺。' },
    { id: 'world-nature-33', group: 'world', category: 'nature_animals', title: '北極狐會換季變色', text: '許多北極狐冬季長出白色厚毛，夏季則轉為棕灰色，配合環境提供掩護。' },
    { id: 'world-nature-34', group: 'world', category: 'nature_animals', title: '鱷魚舌頭不容易伸出來', text: '鱷魚舌頭被組織固定在下顎底部，無法像人類一樣自由伸出口外。' },
    { id: 'world-nature-35', group: 'world', category: 'nature_animals', title: '馴鹿眼睛會季節變色', text: '研究發現馴鹿眼睛反光層會隨季節由金色轉為藍色，幫助適應北極光線變化。' },
    { id: 'world-nature-36', group: 'world', category: 'nature_animals', title: '螳螂蝦看得見偏振光', text: '螳螂蝦擁有複雜眼睛，能偵測人眼看不見的偏振光訊息。' },
    { id: 'world-nature-37', group: 'world', category: 'nature_animals', title: '裸鼴鼠像昆蟲一樣分工', text: '裸鼴鼠群體具有繁殖個體與工作個體的分工，是少見的真社會性哺乳類。' },
    { id: 'world-nature-38', group: 'world', category: 'nature_animals', title: '緩步動物會進入休眠狀態', text: '環境惡劣時，部分緩步動物能縮成休眠狀態，大幅降低代謝並承受極端條件。' },
    { id: 'world-nature-39', group: 'world', category: 'nature_animals', title: '啄木鳥舌頭非常長', text: '許多啄木鳥具有細長舌頭與特殊支撐構造，能深入樹洞捕捉昆蟲。' },
    { id: 'world-nature-40', group: 'world', category: 'nature_animals', title: '榕樹氣根能變成支柱', text: '榕樹從枝幹垂下的氣根接觸土壤後能逐漸增粗，像新的樹幹一樣支撐樹冠。' },

    // 世界探索加碼：科學與太空（16－30）
    { id: 'world-space-16', group: 'world', category: 'science_space', title: '一個 AU 約一億五千萬公里', text: '天文單位 AU 以地球到太陽的平均距離為基準，約為 1.5 億公里。' },
    { id: 'world-space-17', group: 'world', category: 'science_space', title: '太陽寬度約是地球百倍', text: '太陽直徑大約是地球的一百倍，因此體積能容納非常多個地球。' },
    { id: 'world-space-18', group: 'world', category: 'science_space', title: '太陽約四十五億歲', text: '太陽形成於大約 45 億年前，目前大致處於恆星生命的中段。' },
    { id: 'world-space-19', group: 'world', category: 'science_space', title: '內側四顆是岩石行星', text: '水星、金星、地球與火星都有固體表面，被稱為類地行星。' },
    { id: 'world-space-20', group: 'world', category: 'science_space', title: '外側巨行星沒有硬表面', text: '木星、土星、天王星與海王星外層主要由氣體或流體構成，沒有能讓人站立的普通硬表面。' },
    { id: 'world-space-21', group: 'world', category: 'science_space', title: '穀神星也是矮行星', text: '穀神星位於火星與木星之間的小行星帶，也是太陽系正式認定的矮行星之一。' },
    { id: 'world-space-22', group: 'world', category: 'science_space', title: '冥王星有五顆已知衛星', text: '冥王星雖然比地球月球還小，仍擁有包括冥衛一在內的五顆已知衛星。' },
    { id: 'world-space-23', group: 'world', category: 'science_space', title: '冥衛一讓冥王星搖擺', text: '冥衛一相對冥王星非常大，兩者繞共同質心旋轉，看起來像彼此帶著對方搖擺。' },
    { id: 'world-space-24', group: 'world', category: 'science_space', title: '太陽位在獵戶臂附近', text: '太陽系位於銀河系稱為獵戶臂或獵戶支臂的區域。' },
    { id: 'world-space-25', group: 'world', category: 'science_space', title: '旅行者一號進入星際空間', text: 'NASA 的旅行者一號在 2012 年穿越日球層頂，進入星際空間。' },
    { id: 'world-space-26', group: 'world', category: 'science_space', title: '火星一天很像地球', text: '火星自轉一圈約需 24 小時 39 分鐘，只比地球的一天稍長。' },
    { id: 'world-space-27', group: 'world', category: 'science_space', title: '木星大紅斑是巨型風暴', text: '木星大紅斑是一場持續很久的巨大風暴，尺寸與形狀會隨時間改變。' },
    { id: 'world-space-28', group: 'world', category: 'science_space', title: '海王星有超高速風', text: '海王星大氣中的風速可超過每小時兩千公里，是太陽系風速最高的行星之一。' },
    { id: 'world-space-29', group: 'world', category: 'science_space', title: '土星環主要由冰粒組成', text: '土星環由大量冰與岩石碎片構成，小至塵埃、大至巨石都有。' },
    { id: 'world-space-30', group: 'world', category: 'science_space', title: '太陽系有五顆正式矮行星', text: '目前正式認定的五顆矮行星是穀神星、冥王星、妊神星、鳥神星與鬩神星。' },

    // 世界探索加碼：世界與地理（16－30）
    { id: 'world-place-16', group: 'world', category: 'world_places', title: '厄瓜多名字就是赤道', text: 'Ecuador 在西班牙語中是赤道的意思，赤道確實穿過這個國家。' },
    { id: 'world-place-17', group: 'world', category: 'world_places', title: '荷蘭有土地低於海平面', text: '荷蘭部分土地低於海平面，利用堤防、抽水與水利工程管理洪水風險。' },
    { id: 'world-place-18', group: 'world', category: 'world_places', title: '貝加爾湖存著大量淡水', text: '貝加爾湖不只最深，也保存了全球大量未結冰地表淡水。' },
    { id: 'world-place-19', group: 'world', category: 'world_places', title: '格陵蘭是最大島嶼', text: '不把澳洲這個大陸算作島嶼時，格陵蘭是世界面積最大的島。' },
    { id: 'world-place-20', group: 'world', category: 'world_places', title: '亞馬遜河擁有最大流域', text: '亞馬遜河流域是世界最大的河川流域，涵蓋南美洲廣大地區。' },
    { id: 'world-place-21', group: 'world', category: 'world_places', title: '撒哈拉是最大熱沙漠', text: '撒哈拉是世界最大的熱沙漠；若包含寒冷沙漠，南極洲的面積更大。' },
    { id: 'world-place-22', group: 'world', category: 'world_places', title: '安地斯山脈非常長', text: '安地斯山脈沿南美洲西側延伸，是世界最長的陸上山脈之一。' },
    { id: 'world-place-23', group: 'world', category: 'world_places', title: '印尼由上萬座島嶼組成', text: '印度尼西亞是一個大型群島國家，由上萬座島嶼組成。' },
    { id: 'world-place-24', group: 'world', category: 'world_places', title: '玻利維亞有兩座首都', text: '蘇克雷是玻利維亞的憲法首都，政府主要行政機構則位於拉巴斯。' },
    { id: 'world-place-25', group: 'world', category: 'world_places', title: '南非有三座首都', text: '南非把行政、立法與司法首都分設在普勒托利亞、開普敦與布隆方丹。' },
    { id: 'world-place-26', group: 'world', category: 'world_places', title: '中國全國使用同一時區', text: '中國國土橫跨很寬，官方仍統一使用 UTC+8 的北京時間。' },
    { id: 'world-place-27', group: 'world', category: 'world_places', title: '阿拉斯加跨過 180 度經線', text: '阿留申群島跨越 180 度經線，因此阿拉斯加可同時延伸到東半球與西半球。' },
    { id: 'world-place-28', group: 'world', category: 'world_places', title: '吉里巴斯跨越四個半球', text: '吉里巴斯的島嶼分布跨越赤道與接近 180 度經線的兩側，因此橫跨四個半球。' },
    { id: 'world-place-29', group: 'world', category: 'world_places', title: '欽博拉索峰離地心最遠', text: '因地球赤道隆起，厄瓜多的欽博拉索峰頂比聖母峰頂離地球中心更遠。' },
    { id: 'world-place-30', group: 'world', category: 'world_places', title: '裏海是最大內陸水體', text: '裏海雖然名字叫海，卻沒有連接世界海洋，是地球最大的封閉內陸水體。' }
];

const LEGACY_TRIVIA_IDS = [
    ...Array.from({ length: 20 }, (_, index) => `words-${String(index + 1).padStart(2, '0')}`),
    ...Array.from({ length: 20 }, (_, index) => `pronunciation-${String(index + 1).padStart(2, '0')}`),
    ...Array.from({ length: 20 }, (_, index) => `usage-${String(index + 1).padStart(2, '0')}`),
    ...Array.from({ length: 20 }, (_, index) => `world-${String(index + 1).padStart(2, '0')}`),
    ...Array.from({ length: 20 }, (_, index) => `memory-${String(index + 1).padStart(2, '0')}`)
];

// 舊版若已有人抽到卡片，依原收藏冊順序搬到新版，避免更新後收藏數量消失。
export const TRIVIA_LEGACY_ID_MAP = Object.fromEntries(
    LEGACY_TRIVIA_IDS.map((legacyId, index) => [legacyId, TRIVIA_CARDS[index].id])
);
