export const TRIVIA_CATEGORIES = [
    { id: 'words', label: '單字祕密', icon: '🔤', color: 'text-yellow-300' },
    { id: 'pronunciation', label: '發音探索', icon: '🎧', color: 'text-cyan-300' },
    { id: 'usage', label: '常見錯誤', icon: '✍️', color: 'text-red-300' },
    { id: 'world', label: '英語世界', icon: '🌍', color: 'text-green-300' },
    { id: 'memory', label: '記憶技巧', icon: '🧠', color: 'text-purple-300' }
];
export const TRIVIA_SOURCES = {
    words: 'Merriam-Webster、Cambridge Dictionary 與字源資料',
    pronunciation: 'Cambridge Dictionary 與 British Council 發音資料',
    usage: 'Cambridge Grammar 與 British Council 英語教學資料',
    world: 'Cambridge Grammar 與 British Council 英美英語資料',
    memory: 'Dunlosky 等人學習技巧研究與認知心理學研究'
};

export const TRIVIA_CARDS = [
    // 單字祕密（20）
    { id: 'words-01', category: 'words', title: 'alphabet 的開頭', text: 'alphabet 這個字來自希臘字母表前兩個字母 alpha 和 beta。' },
    { id: 'words-02', category: 'words', title: 'emoji 不是 emotion', text: 'emoji 來自日文「繪」和「文字」，只是剛好看起來很像英文 emotion。' },
    { id: 'words-03', category: 'words', title: 'robot 原本是苦工', text: 'robot 來自捷克語 robota，帶有被迫勞動或苦工的意思。' },
    { id: 'words-04', category: 'words', title: 'quarantine 的 40', text: 'quarantine 和義大利語「四十天」有關，早期船隻會被隔離一段時間以防疾病傳播。' },
    { id: 'words-05', category: 'words', title: 'breakfast 在打破什麼？', text: 'breakfast 就是 break 加 fast，意思是結束一整夜沒有進食的狀態。' },
    { id: 'words-06', category: 'words', title: 'goodbye 的祝福', text: 'goodbye 是 God be with ye 逐漸縮短、變化而來的告別語。' },
    { id: 'words-07', category: 'words', title: 'sandwich 是人名', text: 'sandwich 以英國的 Sandwich 伯爵命名，後來成為夾餡麵包的名稱。' },
    { id: 'words-08', category: 'words', title: 'window 是風之眼', text: 'window 的早期字源和古北歐語的「風之眼」有關，形容牆上讓風與光進入的開口。' },
    { id: 'words-09', category: 'words', title: 'clue 原本是一團線', text: 'clue 以前也寫作 clew，原意是一團線；故事裡的線能帶人走出迷宮，後來變成「線索」。' },
    { id: 'words-10', category: 'words', title: 'muscle 像小老鼠', text: 'muscle 來自拉丁語「小老鼠」，古人覺得肌肉在皮膚下移動的樣子像老鼠。' },
    { id: 'words-11', category: 'words', title: 'companion 一起吃麵包', text: 'companion 的字源包含「一起」和「麵包」，原本指一起分享食物的人。' },
    { id: 'words-12', category: 'words', title: 'candidate 穿白衣', text: 'candidate 和拉丁語的「潔白」有關，古羅馬的候選人會穿著特別處理過的白袍。' },
    { id: 'words-13', category: 'words', title: 'disaster 是壞星象', text: 'disaster 的字源可拆成「不好的」和「星星」，反映古人把災禍和星象聯繫在一起。' },
    { id: 'words-14', category: 'words', title: '& 也有名字', text: '& 叫做 ampersand，它的形狀是拉丁文 et（and）長期連寫形成的。' },
    { id: 'words-15', category: 'words', title: '大小寫來自盒子', text: 'uppercase 和 lowercase 來自早期印刷工坊：大寫鉛字放在上層盒子，小寫放在下層盒子。' },
    { id: 'words-16', category: 'words', title: '先有水果才有顏色', text: '英文 orange 先是水果名稱，後來才成為橘色的顏色名稱。' },
    { id: 'words-17', category: 'words', title: '三組連續雙字母', text: 'bookkeeper 有 oo、kk、ee 三組連續的雙字母，是很少見的拼字。' },
    { id: 'words-18', category: 'words', title: '15 個字母不重複', text: 'uncopyrightable 有 15 個字母，而且沒有任何字母重複。' },
    { id: 'words-19', category: 'words', title: 'queue 只聽見一個字母', text: 'queue 的發音和字母 Q 相同，後面的 ueue 在現代英語發音中都沒有各自發聲。' },
    { id: 'words-20', category: 'words', title: '矛盾修辭本身也矛盾', text: 'oxymoron 指把看似矛盾的詞放在一起；它的希臘字源本身就有「敏銳」與「愚鈍」的組合。' },

    // 發音探索（20）
    { id: 'pronunciation-01', category: 'pronunciation', title: '最常出現的弱母音', text: 'schwa 寫作 /ə/，常出現在沒有重音的音節，例如 about 的第一個音。' },
    { id: 'pronunciation-02', category: 'pronunciation', title: '重音比大聲更重要', text: '英文重音通常同時包含較清楚的母音、較長的時間和音高變化，不只是把聲音放大。' },
    { id: 'pronunciation-03', category: 'pronunciation', title: 'REcord 與 reCORD', text: 'record 當名詞時常把重音放前面，當動詞時常放後面；重音可能幫助分辨詞性。' },
    { id: 'pronunciation-04', category: 'pronunciation', title: '複數 s 有三種聲音', text: '英文複數字尾常讀成 /s/、/z/ 或 /ɪz/，要看前一個聲音，而不是只看字母。' },
    { id: 'pronunciation-05', category: 'pronunciation', title: '過去式 ed 也有三種', text: '規則動詞的 -ed 常讀成 /t/、/d/ 或 /ɪd/，例如 worked、played、wanted。' },
    { id: 'pronunciation-06', category: 'pronunciation', title: 'th 有兩種聲帶狀態', text: 'think 的 th 不振動聲帶，this 的 th 會振動；兩者的舌頭位置很接近。' },
    { id: 'pronunciation-07', category: 'pronunciation', title: 'kn 的 k 通常沉默', text: 'know、knee、knife 開頭的 k 在現代英語通常不發音。' },
    { id: 'pronunciation-08', category: 'pronunciation', title: 'mb 結尾的 b', text: 'lamb、climb、thumb 結尾的 b 通常不發音，但字母仍保留在拼字中。' },
    { id: 'pronunciation-09', category: 'pronunciation', title: 'gh 最會變化', text: 'gh 在 night 中不發音，在 laugh 中可讀 /f/，在 ghost 中則是 /g/ 的一部分。' },
    { id: 'pronunciation-10', category: 'pronunciation', title: 'c 的常見規律', text: 'c 在 e、i、y 前常讀 /s/，其他位置常讀 /k/，例如 city 和 cat。' },
    { id: 'pronunciation-11', category: 'pronunciation', title: 'g 有規律也有例外', text: 'g 在 e、i、y 前常讀 /dʒ/，但 get、give 等常用字是明顯例外。' },
    { id: 'pronunciation-12', category: 'pronunciation', title: 'ch 不只一種讀法', text: 'ch 在 chair 常讀 /tʃ/，在 chemistry 常讀 /k/，在 machine 常讀 /ʃ/。' },
    { id: 'pronunciation-13', category: 'pronunciation', title: 'x 也能變聲', text: 'x 在 box 常讀 /ks/，在 exam 常讀 /gz/，在 xylophone 開頭常讀 /z/。' },
    { id: 'pronunciation-14', category: 'pronunciation', title: 'oo 不保證同音', text: 'food 和 foot 都有 oo，但母音不同；英文拼字不能永遠直接預測發音。' },
    { id: 'pronunciation-15', category: 'pronunciation', title: '同拼字也可能不同音', text: 'lead 可以是「帶領」/liːd/，也可以是金屬「鉛」/led/，要靠句子判斷。' },
    { id: 'pronunciation-16', category: 'pronunciation', title: '不同拼字可以同音', text: 'see 和 sea、right 和 write 是同音字；只聽聲音時要靠上下文理解。' },
    { id: 'pronunciation-17', category: 'pronunciation', title: '口音不等於錯誤', text: '英語在世界各地有許多自然口音；能否清楚溝通，比模仿唯一一種口音更重要。' },
    { id: 'pronunciation-18', category: 'pronunciation', title: '有些口音會保留 r', text: '許多美式口音會讀出 car 結尾的 r；許多英格蘭口音在後面沒有母音時不讀這個 r。' },
    { id: 'pronunciation-19', category: 'pronunciation', title: '問號不一定上揚', text: 'Yes／No 問句常出現上揚語調，但語氣、重點與口音都可能改變實際音調。' },
    { id: 'pronunciation-20', category: 'pronunciation', title: '弱讀讓英文更自然', text: 'and、to、of 等功能字在自然句子中常被弱讀，這也是英文節奏的重要部分。' },

    // 常見錯誤（20）
    { id: 'usage-01', category: 'usage', title: 'fewer 與 less', text: '可數的東西通常用 fewer，不可數的量通常用 less，例如 fewer books、less water。' },
    { id: 'usage-02', category: 'usage', title: 'many 與 much', text: 'many 通常搭配可數複數，much 通常搭配不可數名詞，例如 many ideas、much time。' },
    { id: 'usage-03', category: 'usage', title: 'advice 不能直接數', text: 'advice 是不可數名詞；可以說 some advice 或 a piece of advice。advise 則是動詞。' },
    { id: 'usage-04', category: 'usage', title: 'affect 與 effect', text: 'affect 最常當「影響」的動詞，effect 最常當「效果」的名詞，但兩者都有較少見的其他用法。' },
    { id: 'usage-05', category: 'usage', title: 'its 沒有撇號', text: 'its 表示「它的」；it’s 是 it is 或 it has 的縮寫。' },
    { id: 'usage-06', category: 'usage', title: '三個同音字', text: 'there 表示地點或存在，their 表示「他們的」，they’re 是 they are。' },
    { id: 'usage-07', category: 'usage', title: 'since 與 for', text: 'since 常接起點，例如 since Monday；for 常接一段時間，例如 for three days。' },
    { id: 'usage-08', category: 'usage', title: 'say 與 tell', text: 'say 著重說出的內容；tell 後面常直接接聽話的人，例如 tell me the truth。' },
    { id: 'usage-09', category: 'usage', title: 'borrow 與 lend', text: 'borrow 是向別人借進來，lend 是把東西借出去；方向正好相反。' },
    { id: 'usage-10', category: 'usage', title: '人 interested，事 interesting', text: 'interested 描述人的感受；interesting 描述讓人產生這種感受的事物。' },
    { id: 'usage-11', category: 'usage', title: 'fun 不等於 funny', text: 'fun 通常表示好玩；funny 常表示好笑，也可能表示奇怪。' },
    { id: 'usage-12', category: 'usage', title: 'actually 不是目前', text: 'actually 常表示「其實」；「目前」通常用 currently 或 at the moment。' },
    { id: 'usage-13', category: 'usage', title: 'homework 不加 s', text: 'homework 通常是不可數名詞；可以說 a lot of homework，但通常不說 homeworks。' },
    { id: 'usage-14', category: 'usage', title: 'information 也不可數', text: 'information 通常不加 s；一項資訊可以說 a piece of information。' },
    { id: 'usage-15', category: 'usage', title: 'news 看似複數卻用單數', text: 'news 雖然以 s 結尾，現代英文通常把它當單數，例如 The news is good。' },
    { id: 'usage-16', category: 'usage', title: 'agree 前面不用 be', text: 'agree 本身是動詞，所以說 I agree，不說 I am agree。' },
    { id: 'usage-17', category: 'usage', title: 'discuss 後面直接接主題', text: 'discuss 通常直接接受詞，例如 discuss the problem，不需要再加 about。' },
    { id: 'usage-18', category: 'usage', title: 'look forward to 後接 ing', text: 'look forward to 裡的 to 是介系詞，所以後面常接名詞或動名詞，例如 looking forward to meeting you。' },
    { id: 'usage-19', category: 'usage', title: 'person 和 people', text: '一個人是 one person，多個人通常是 people；persons 多用在正式或法律語境。' },
    { id: 'usage-20', category: 'usage', title: 'make 與 do 的搭配', text: '英文常說 make a decision、make a mistake，但說 do homework、do the dishes；這些搭配需要一起記。' },

    // 英語世界（20）
    { id: 'world-01', category: 'world', title: 'flat 與 apartment', text: '英式英文常說 flat，美式英文常說 apartment，兩者都可以表示公寓住宅。' },
    { id: 'world-02', category: 'world', title: 'lift 與 elevator', text: '英式英文常說 lift，美式英文常說 elevator。' },
    { id: 'world-03', category: 'world', title: 'chips 到底是哪一種？', text: '英國的 chips 通常是炸薯條；美國的 chips 通常是薄脆薯片。' },
    { id: 'world-04', category: 'world', title: '英國的 crisps', text: '英國人常用 crisps 指袋裝薄薯片，美國人通常稱它們 potato chips。' },
    { id: 'world-05', category: 'world', title: 'football 與 soccer', text: '世界許多地方的 football 指足球；在美國，football 通常指美式足球，足球常叫 soccer。' },
    { id: 'world-06', category: 'world', title: 'colour 和 color 都對', text: 'colour 常見於英式拼字，color 常見於美式拼字；差異不代表其中一個必然錯誤。' },
    { id: 'world-07', category: 'world', title: 'centre 和 center', text: 'centre 是常見英式拼字，center 是常見美式拼字。' },
    { id: 'world-08', category: 'world', title: 'travelled 和 traveled', text: '英式英文常寫 travelled，美式英文通常寫 traveled；兩邊的雙寫規則略有差異。' },
    { id: 'world-09', category: 'world', title: 'autumn 和 fall 都很老', text: 'autumn 和 fall 都能表示秋天；fall 並不是現代美國才新造出的詞。' },
    { id: 'world-10', category: 'world', title: 'pants 的英美差異', text: '美式英文的 pants 通常是長褲；英式英文的 pants 常指內褲，長褲常叫 trousers。' },
    { id: 'world-11', category: 'world', title: 'first floor 不一定同一層', text: '美國的 first floor 通常是地面層；英國常把地面層叫 ground floor，上一層才是 first floor。' },
    { id: 'world-12', category: 'world', title: 'biscuit 和 cookie', text: '英國的 biscuit 範圍包含許多甜脆點心；美國的 biscuit 也可能指一種鬆軟鹹麵包。' },
    { id: 'world-13', category: 'world', title: 'holiday 和 vacation', text: '英式英文常用 holiday 表示休假旅行；美式英文更常用 vacation。' },
    { id: 'world-14', category: 'world', title: 'queue 和 line', text: '排隊在英式英文常說 queue，在美式英文常說 stand in line 或 wait in line。' },
    { id: 'world-15', category: 'world', title: 'postcode 和 ZIP code', text: '英國地址使用 postcode；美國使用 ZIP code。' },
    { id: 'world-16', category: 'world', title: 'mobile phone 和 cell phone', text: '英國常說 mobile phone，美國常說 cell phone。' },
    { id: 'world-17', category: 'world', title: 'gotten 並沒有消失', text: '美式英文常用 gotten 作 get 的過去分詞；英式英文較常使用 got。' },
    { id: 'world-18', category: 'world', title: 'already 的時態差異', text: '英式英文常用現在完成式搭配 already；美式英文在相同情況下也常使用過去式。' },
    { id: 'world-19', category: 'world', title: '球隊可以是 they', text: '英式英文較常把球隊等集合名詞視為一群人而使用複數動詞；美式英文較常使用單數。' },
    { id: 'world-20', category: 'world', title: '英文沒有唯一標準口音', text: '英語在不同國家與地區形成多種成熟用法；字典也常同時提供英式與美式發音。' },

    // 記憶技巧（20）
    { id: 'memory-01', category: 'memory', title: '分開練比一次塞完更穩', text: '把同樣的練習分散到不同日期，通常比在同一天集中重複更有利於長期記憶。' },
    { id: 'memory-02', category: 'memory', title: '小測驗也是學習', text: '主動從記憶中找答案的練習，不只是檢查程度，也能幫助之後記得更久。' },
    { id: 'memory-03', category: 'memory', title: '看得熟不等於想得起來', text: '重讀時產生的熟悉感，可能讓人高估自己之後能不能在沒有提示時回答。' },
    { id: 'memory-04', category: 'memory', title: '只畫重點通常不夠', text: '畫線或螢光筆如果沒有搭配回想、提問或整理，學習效果通常有限。' },
    { id: 'memory-05', category: 'memory', title: '交錯練習幫助辨認題型', text: '把幾種容易混淆的內容交錯練習，可能比一次只練一種類型更能訓練判斷。' },
    { id: 'memory-06', category: 'memory', title: '解釋給自己聽', text: '用自己的話說明答案為什麼成立，可以幫助連結新知識與原有理解。' },
    { id: 'memory-07', category: 'memory', title: '多問一個為什麼', text: '學習事實時追問「為什麼這是對的」，能促使大腦建立更多有意義的連結。' },
    { id: 'memory-08', category: 'memory', title: '錯後的回饋很重要', text: '答錯後得到清楚的正確答案與解釋，可以避免把原本的錯誤繼續練熟。' },
    { id: 'memory-09', category: 'memory', title: '睡眠會參與記憶整理', text: '睡眠不只是休息；大腦會在睡眠期間進行和記憶穩定有關的處理。' },
    { id: 'memory-10', category: 'memory', title: '忘記不是完全失敗', text: '一時想不起來不代表全部消失；重新成功回想，可能讓之後的記憶更穩。' },
    { id: 'memory-11', category: 'memory', title: '先猜再看答案', text: '看到答案前先嘗試回想，通常比直接閱讀答案更能暴露自己真正不熟的地方。' },
    { id: 'memory-12', category: 'memory', title: '有點費力可能是好事', text: '在仍有機會成功、而且之後有正確回饋的情況下，較費力的回想可能帶來更穩的記憶。' },
    { id: 'memory-13', category: 'memory', title: '短練習也能累積', text: '多次短時間練習若分散進行，通常比偶爾一次很長的臨時抱佛腳更容易維持。' },
    { id: 'memory-14', category: 'memory', title: '雙向都要練', text: '只看英文選中文，可能不代表看到中文也想得起英文；換方向練習能暴露不同弱點。' },
    { id: 'memory-15', category: 'memory', title: '自己造例句更有連結', text: '把新單字放進和自己生活有關的句子，通常比只抄別人的例句多一層思考。' },
    { id: 'memory-16', category: 'memory', title: '分組能減少負擔', text: '把長資訊整理成有意義的小組塊，可以減少工作記憶一次需要處理的單位。' },
    { id: 'memory-17', category: 'memory', title: '文字加圖像要互相幫忙', text: '文字配上真正能說明概念的圖片，可能比裝飾性圖片更能幫助理解與回想。' },
    { id: 'memory-18', category: 'memory', title: '換情境練習', text: '在不同句子與題型中遇到同一個字，可以幫助理解它不只會出現在原本那一題。' },
    { id: 'memory-19', category: 'memory', title: '答案認得，不代表能說出', text: '選擇題中的「看得出正解」和沒有選項時「自己想出答案」是不同難度的能力。' },
    { id: 'memory-20', category: 'memory', title: '錯題是下一步的地圖', text: '錯題能指出目前最容易混淆的位置；隔一段時間重新作答，比只看一次解析更有價值。' }
];
