import { createHash } from 'node:crypto';
import {
    copyFileSync,
    existsSync,
    mkdirSync,
    readFileSync,
    renameSync,
    statSync,
    writeFileSync
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildTtsInventory } from './tts_inventory.mjs';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(scriptDirectory, '..');
const envPath = join(projectRoot, '.env');
const outputRoot = join(projectRoot, 'public', 'audio', 'tts', 'library');
const statePath = join(projectRoot, 'scripts', 'tts-full-generation-log.json');
const generatedModulePath = join(projectRoot, 'src', 'constants', 'ttsAudioData.js');
const voices = ['marin', 'cedar'];
const model = 'gpt-4o-mini-tts';
const args = new Set(process.argv.slice(2));
const dryRun = args.has('--dry-run');
const concurrencyArg = process.argv.find(arg => arg.startsWith('--concurrency='));
const limitArg = process.argv.find(arg => arg.startsWith('--limit='));
const concurrency = Math.max(1, Math.min(8, Number(concurrencyArg?.split('=')[1]) || 6));
const limit = Math.max(0, Number(limitArg?.split('=')[1]) || 0);

const loadEnvValue = (key) => {
    if (!existsSync(envPath)) return '';
    const line = readFileSync(envPath, 'utf8')
        .split(/\r?\n/)
        .find(entry => entry.trim().startsWith(`${key}=`));
    if (!line) return '';
    return line.slice(line.indexOf('=') + 1).trim().replace(/^(['"])(.*)\1$/, '$2');
};

const inventory = buildTtsInventory(projectRoot);
if (inventory.entryKeyCollisions.length > 0) {
    throw new Error(`發音清單有 ${inventory.entryKeyCollisions.length} 個索引碰撞，停止產生。`);
}

const toObjectLiteral = (mapping) => JSON.stringify(Object.fromEntries(mapping), null, 4);
const generatedModule = `// Generated by scripts/generate_tts_all.mjs. Do not edit manually.
const audioByEntry = ${toObjectLiteral(inventory.entryMappings)};

const audioByFallback = ${toObjectLiteral(inventory.fallbackMappings)};

const normalize = (value) => String(value ?? '').trim().replace(/\\s+/g, ' ').toLowerCase();

const makeEntryKey = (item = {}) => {
    const location = item.series === 'advanced'
        ? \`advanced|\${item.lesson}\`
        : \`textbook|\${item.book}|\${item.unit}\`;
    return [
        location,
        normalize(item.category),
        normalize(item.word),
        normalize(item.chinese)
    ].join('|');
};

export const getTtsAudio = (item = {}) => {
    const stem = audioByEntry[makeEntryKey(item)]
        || audioByFallback[[normalize(item.word), normalize(item.chinese)].join('|')];
    if (!stem) return null;
    const basePath = '/audio/tts/library';
    return {
        marin: \`\${basePath}/marin/\${stem}.mp3\`,
        cedar: \`\${basePath}/cedar/\${stem}.mp3\`
    };
};
`;
writeFileSync(generatedModulePath, generatedModule, 'utf8');

const summary = {
    ...inventory.sourceSummary,
    voices,
    requestedFiles: inventory.specs.length * voices.length,
    concurrency,
    dryRun
};
console.log(JSON.stringify(summary, null, 2));
if (dryRun) process.exit(0);

const apiKey = process.env.OPENAI_API_KEY || loadEnvValue('OPENAI_API_KEY');
if (!apiKey) throw new Error('找不到 OPENAI_API_KEY；請確認專案根目錄的 .env 已設定。');

mkdirSync(outputRoot, { recursive: true });
const emptyState = {
    model,
    voices,
    sourceSummary: inventory.sourceSummary,
    items: {}
};
const generationState = existsSync(statePath)
    ? JSON.parse(readFileSync(statePath, 'utf8'))
    : emptyState;

const saveState = () => {
    const temporaryPath = `${statePath}.tmp`;
    writeFileSync(temporaryPath, `${JSON.stringify(generationState, null, 2)}\n`, 'utf8');
    renameSync(temporaryPath, statePath);
};

const lesson133Filenames = new Map([
    ['after', '001-after'],
    ['although', '002-although'],
    ['and', '003-and'],
    ['as', '004-as'],
    ['because', '005-because'],
    ['before', '006-before'],
    ['but', '007-but'],
    ['either or', '008-either-or'],
    ['if', '009-if'],
    ['neither nor', '010-neither-nor'],
    ['or', '011-or'],
    ['since', '012-since'],
    ['so', '013-so'],
    ['so... that', '014-so-that'],
    ['then', '015-then'],
    ['when', '016-when'],
    ['while', '017-while']
]);

const seedFromLesson133 = (spec, voice, targetPath) => {
    const occurrence = spec.occurrences.find(entry => Number(entry.lesson) === 133);
    if (!occurrence) return false;
    const oldFilename = lesson133Filenames.get(occurrence.word.toLowerCase());
    if (!oldFilename) return false;
    const oldPath = join(
        projectRoot,
        'public',
        'audio',
        'tts',
        'advanced',
        'lesson-133',
        voice,
        `${oldFilename}.mp3`
    );
    if (!existsSync(oldPath) || statSync(oldPath).size <= 500) return false;
    copyFileSync(oldPath, targetPath);
    return true;
};

const makeInstructions = (spec) => [
    'Pronounce only the supplied English vocabulary item or pattern.',
    'Use clear, natural General American English for Taiwanese English learners.',
    'Use a calm teaching voice at a slightly slower-than-normal pace.',
    'Do not add an introduction, definition, example, spelling, labels, or commentary.',
    spec.instruction
].filter(Boolean).join(' ');

const sleep = (milliseconds) => new Promise(resolve => setTimeout(resolve, milliseconds));

const requestSpeech = async (task) => {
    let lastError;
    for (let attempt = 1; attempt <= 5; attempt += 1) {
        try {
            const response = await fetch('https://api.openai.com/v1/audio/speech', {
                method: 'POST',
                headers: {
                    Authorization: `Bearer ${apiKey}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    model,
                    voice: task.voice,
                    input: task.spec.spokenText,
                    instructions: makeInstructions(task.spec),
                    response_format: 'mp3'
                })
            });

            if (!response.ok) {
                const body = (await response.text()).replaceAll(apiKey, '[REDACTED]');
                const error = new Error(`HTTP ${response.status}: ${body.slice(0, 500)}`);
                error.retryable = response.status === 429 || response.status >= 500;
                throw error;
            }

            const contentType = response.headers.get('content-type') || '';
            const buffer = Buffer.from(await response.arrayBuffer());
            if (!contentType.includes('audio') || buffer.length <= 500) {
                throw new Error(`音檔格式異常：${contentType || '無 Content-Type'}，${buffer.length} bytes`);
            }
            return buffer;
        } catch (error) {
            lastError = error;
            if (error.retryable === false || attempt === 5) break;
            await sleep(Math.min(15000, 750 * (2 ** (attempt - 1))));
        }
    }
    throw lastError;
};

const tasks = [];
for (const spec of inventory.specs) {
    for (const voice of voices) {
        const voiceDirectory = join(outputRoot, voice);
        mkdirSync(voiceDirectory, { recursive: true });
        const filePath = join(voiceDirectory, `${spec.stem}.mp3`);
        const stateKey = `${voice}:${spec.id}`;

        if (existsSync(filePath) && statSync(filePath).size > 500) {
            const buffer = readFileSync(filePath);
            generationState.items[stateKey] = {
                voice,
                specId: spec.id,
                stem: spec.stem,
                displayText: spec.displayText,
                spokenText: spec.spokenText,
                status: 'completed',
                bytes: buffer.length,
                sha256: createHash('sha256').update(buffer).digest('hex'),
                completedAt: generationState.items[stateKey]?.completedAt || null,
                source: generationState.items[stateKey]?.source || 'existing'
            };
            continue;
        }

        if (seedFromLesson133(spec, voice, filePath)) {
            const buffer = readFileSync(filePath);
            generationState.items[stateKey] = {
                voice,
                specId: spec.id,
                stem: spec.stem,
                displayText: spec.displayText,
                spokenText: spec.spokenText,
                status: 'completed',
                bytes: buffer.length,
                sha256: createHash('sha256').update(buffer).digest('hex'),
                completedAt: new Date().toISOString(),
                source: 'lesson-133-pilot'
            };
            continue;
        }

        tasks.push({ spec, voice, filePath, stateKey });
    }
}
saveState();

const pendingTasks = limit > 0 ? tasks.slice(0, limit) : tasks;
let completedThisRun = 0;
let nextIndex = 0;
let failed = false;

const worker = async () => {
    while (!failed) {
        const index = nextIndex;
        nextIndex += 1;
        if (index >= pendingTasks.length) return;
        const task = pendingTasks[index];

        try {
            const buffer = await requestSpeech(task);
            const temporaryPath = `${task.filePath}.tmp`;
            writeFileSync(temporaryPath, buffer);
            renameSync(temporaryPath, task.filePath);
            generationState.items[task.stateKey] = {
                voice: task.voice,
                specId: task.spec.id,
                stem: task.spec.stem,
                displayText: task.spec.displayText,
                spokenText: task.spec.spokenText,
                status: 'completed',
                bytes: buffer.length,
                sha256: createHash('sha256').update(buffer).digest('hex'),
                completedAt: new Date().toISOString(),
                source: 'openai'
            };
            completedThisRun += 1;
            if (completedThisRun % 10 === 0 || completedThisRun === pendingTasks.length) {
                saveState();
                console.log(`進度：${completedThisRun}/${pendingTasks.length}（總完成 ${Object.keys(generationState.items).length}/${inventory.specs.length * voices.length}）`);
            }
        } catch (error) {
            failed = true;
            saveState();
            console.error(`失敗：${task.voice} / ${task.spec.displayText} / ${error.message}`);
            throw error;
        }
    }
};

console.log(`已存在或沿用：${inventory.specs.length * voices.length - tasks.length}；本次待產生：${pendingTasks.length}`);
await Promise.all(Array.from({ length: Math.min(concurrency, pendingTasks.length || 1) }, worker));
saveState();
console.log(`完成：${Object.keys(generationState.items).length}/${inventory.specs.length * voices.length} 個音檔。`);
